# Generated by Django 4.2.3 on 2025-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='Is Administrator'),
        ),
    ]
