# Generated by Django 4.2.3 on 2025-06-24 10:25

import apps.incident.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='শিরনাম')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='বিস্তারিত')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='অক্ষাংশ (ল্যাটিচুয়েড)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='দ্রাঘিমাংশ (লংগিচুয়েড)')),
                ('date', models.DateTimeField(verbose_name='ঘটনার তারিখ এবং সুময়')),
                ('status', models.CharField(choices=[('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED'), ('ARCHIVED', 'ARCHIVED')], default='PUBLISHED', max_length=12, verbose_name='পাবলিশিং স্ট্যাটাস')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.district', verbose_name='জেলা')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.division', verbose_name='বিভাগ')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'db_incidents',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=100, verbose_name='ঘটনার ধরণ (বাংলা)')),
                ('name_en', models.CharField(max_length=100, verbose_name='ঘটনার ধরণ (ইংরেজি)')),
            ],
            options={
                'verbose_name': 'Incident Type',
                'verbose_name_plural': 'Incident Type',
                'db_table': 'db_incident_type',
                'ordering': ('name_bn',),
            },
        ),
        migrations.CreateModel(
            name='InvolvedActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=255, verbose_name='জড়িত ব্যক্তি/গোষ্ঠী/সংগঠন (বাংলা)')),
                ('name_en', models.CharField(max_length=255, verbose_name='জড়িত ব্যক্তি/গোষ্ঠী/সংগঠন (ইংরেজি)')),
            ],
            options={
                'verbose_name': 'Involved Actor',
                'verbose_name_plural': 'Involved Actor',
                'db_table': 'db_involved_actor',
                'ordering': ('name_bn',),
            },
        ),
        migrations.CreateModel(
            name='IncidentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=apps.incident.utils.incident_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='ছবি')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_images', to='incident.incident', verbose_name='ইন্সিডেন্ট')),
            ],
            options={
                'verbose_name': 'জেলা',
                'verbose_name_plural': 'জেলা',
                'db_table': 'db_incident_images',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='incident.incidenttype', verbose_name='ঘটনার ধরণ'),
        ),
        migrations.AddField(
            model_name='incident',
            name='involved_actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_actors', to='incident.involvedactor', verbose_name='জড়িত ব্যক্তি/গোষ্ঠী/সংগঠন'),
        ),
        migrations.AddField(
            model_name='incident',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_posted_user', to=settings.AUTH_USER_MODEL, verbose_name='রিপোর্টারের নাম'),
        ),
        migrations.AddField(
            model_name='incident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='পরিপোর্ট হালনাগাদ কারীর নাম'),
        ),
    ]
