# Generated by Django 4.2.3 on 2025-06-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentimage',
            options={'verbose_name': 'Incident Image', 'verbose_name_plural': 'Incident Images'},
        ),
    ]
