# Generated by Django 4.2.3 on 2025-08-02 22:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_state_subdistrict'),
        ('incident', '0002_alter_incidentimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='রাষ্ট্র/দেশ'),
        ),
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_states', to='location.state', verbose_name='স্টেট/রাজ্য'),
        ),
        migrations.AddField(
            model_name='incident',
            name='subdistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_subdistricts', to='location.subdistrict', verbose_name='উপজেলার নাম'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_districts', to='location.district', verbose_name='জেলা'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_divisions', to='location.division', verbose_name='বিভাগ'),
        ),
    ]
