# Generated by Django 4.2.3 on 2025-08-17 09:25

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_incident_country_incident_state_incident_subdistrict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='রাষ্ট্র/দেশ'),
        ),
        migrations.AddField(
            model_name='involvedactor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='রাষ্ট্র/দেশ'),
        ),
    ]
