# Generated by Django 4.2.3 on 2025-06-24 10:25

import apps.location.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=25, verbose_name='বিভাগের নাম')),
                ('name_en', models.CharField(blank=True, max_length=25, null=True, verbose_name='বিভাগের নাম (ইংরেজিতে)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.location.utils.division_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='বিভাগের ম্যাপ')),
            ],
            options={
                'verbose_name': 'বিভাগ',
                'verbose_name_plural': 'বিভাগ',
                'db_table': 'db_division',
                'ordering': ('name_bn',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=30, verbose_name='জেলার নাম')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='জেলার নাম (ইংরেজিতে)')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.location.utils.district_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='জেলার ম্যাপ')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.division', verbose_name='বিভাগের নাম')),
            ],
            options={
                'verbose_name': 'জেলা',
                'verbose_name_plural': 'জেলা',
                'db_table': 'db_district',
                'ordering': ('name_bn',),
            },
        ),
    ]
