# Generated by Django 4.2.3 on 2025-06-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ('name_bn',), 'verbose_name': 'District', 'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name_bn',), 'verbose_name': 'Division', 'verbose_name_plural': 'Division'},
        ),
    ]
