# Generated by Django 4.2.3 on 2025-08-02 22:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_district_options_alter_division_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=30, verbose_name='স্টেট/রাজ্য নাম')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='স্টেট নাম (ইংরেজিতে)')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='রাষ্ট্র/দেশ')),
            ],
            options={
                'verbose_name': 'স্টেট',
                'verbose_name_plural': 'স্টেট',
                'db_table': 'db_states',
                'ordering': ('name_bn',),
            },
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bn', models.CharField(max_length=30, verbose_name='উপজেলার নাম')),
                ('name_en', models.CharField(blank=True, max_length=30, null=True, verbose_name='উপজেলার নাম (ইংরেজিতে)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdistricts', to='location.district', verbose_name='জেলার নাম')),
            ],
            options={
                'verbose_name': 'উপজেলা',
                'verbose_name_plural': 'উপজেলা',
                'db_table': 'db_subdistrict',
                'ordering': ('name_bn',),
            },
        ),
    ]
