# Generated by Django 4.2.3 on 2025-08-02 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_state_subdistrict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('name_bn',), 'verbose_name': 'State', 'verbose_name_plural': 'State'},
        ),
        migrations.AlterModelOptions(
            name='subdistrict',
            options={'ordering': ('name_bn',), 'verbose_name': 'Sub-District', 'verbose_name_plural': 'Sub-District'},
        ),
    ]
